name: Pull requests
on:
  pull_request:
    branches-ignore:
      - 'snyk-*'
      - 'dependabot-*'
jobs:
  call_npm_package_build:
    uses: szikszail/workflows/.github/workflows/npm-package-build.yml@v1
